// Static export compatibility: pre-generate the brief at build time.
// When deployed with `output: "export"`, Next.js cannot serve dynamic API routes.
// The main page fetches /api/brief/data.json instead (generated by build-pages.sh).

export const dynamic = "force-static";

import { NextResponse } from "next/server";
import { generateGrowthBrief } from "@/lib/brief";
import { mockCharts, mockOverview } from "@/lib/mock-data";

const CHARTS = ["revenue", "mrr", "trial_conversion_rate", "churn", "customers_new", "trials"] as const;

export async function GET() {
  // Static export always uses mock data (no server-side secrets available).
  // For live data, run locally with REVENUECAT_API_KEY set.
  const overview = mockOverview;
  const chartResponses = CHARTS.map((name) => mockCharts[name]);

  const chartMap = Object.fromEntries(CHARTS.map((name, i) => [name, chartResponses[i]]));
  const brief = generateGrowthBrief({
    overview: overview.metrics,
    charts: {
      revenue: chartMap.revenue,
      mrr: chartMap.mrr,
      trial_conversion_rate: chartMap.trial_conversion_rate,
      churn: chartMap.churn,
      customers_new: chartMap.customers_new,
      trials: chartMap.trials,
    },
  });

  return NextResponse.json({
    generated_at: new Date().toISOString(),
    mode: "mock",
    brief,
  });
}
